canva/blog/urls.py
from django.urls import path
from . import views

app_name='blog'


urlpatterns = [
    path("blog/",views.blog,name="blog"),
    path("blog_detail/<int:id>/",views.blog_detail,name="blog-detail"),
    path("article-form/",views.add_article,name="article-form"),
    path("edit-article/<int:id>/",views.article_edit,name="edit-article"),
    path("delete-article/<int:id>/",views.delete_article,name="delete-article"),
    path("example/",views.example,name="example"),
]

canva/canva/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls")),
    path('user/', include('user.urls')),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canva/info/urls.py
from django.urls import path
from . import  views

app_name='info'
urlpatterns=[
    path('', views.home, name='home'),
    path("contact/",views.contact,name='Contact'),
    path("confirm-contact/",views.confirm_contact,name='confirm_contact'),
]

canva/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    title=models.CharField(max_length=10)
    def __str__(self):
        return self.title

class Author(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username
    

class Article(models.Model):
    title=models.CharField(max_length=50)
    description=models.TextField(null=True,blank=True)
    content=models.TextField()
    show=models.BooleanField(default=True)
    view_count=models.IntegerField(default=0)
    image=models.ImageField(null=True,blank=True)
    created=models.DateField(auto_now_add=True)
    author=models.ForeignKey(Author,on_delete=models.CASCADE,null=True,blank=True)
    tags=models.ManyToManyField(Tag)
    
    def __str__(self):
        return self.title
    
class ArticleImage(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='article_images/')


canva/blog/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model=Article
        
        exclude=['view_count','author']
    
    def save(self,author):
        instance=super().save()
        instance.author=author
        instance.save()
        return instance

canva/blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Article,Author,Tag
from django.core.exceptions import PermissionDenied
from .forms import ArticleForm
from django.core.paginator import Paginator
def blog(request):
    author_username=request.GET.get("author")
    authors=Article.objects.all()
    articles=Article.objects.all()
    tags=Tag.objects.all()
    tag_title=request.GET.get("tag")
    page_number=int(request.GET.get('page',1))
    if author_username:
        articles=articles.filter(author__user__username=author_username)
    if tag_title:
        articles=articles.filter(tags__title=tag_title)
    paginator=Paginator(articles,3)
    page=paginator.page(page_number)
    articles=page.object_list
    return render(request,"blog.html",context={'articles':articles,'authors':authors,'tags':tags,'paginator':paginator,'page':page})



def blog_detail(request, id):
    article = Article.objects.get(id=id)
    return render(request, "blog-detail.html", context={'article': article})

def add_article(request):
    if request.method=='POST':
        data=request.POST.copy()
        form=ArticleForm(data=data,files=request.FILES)
        if form.is_valid():
            form.save(request.user.author)
            return redirect('blog:blog')
    else:
        form=ArticleForm()
        return render(request,"article-form.html",{'form':form})
    
    

def article_edit(request,id):
    article=get_object_or_404(Article,id=id)
    if article.author.user != request.user:
        raise PermissionDenied()
    if request.method == "POST":
        data=request.POST.copy()
        data['author']=request.user.author.id
        form=ArticleForm(data=data,files=request.FILES,instance=article)
        if form.is_valid:
            form.save(request.user.author)
            return redirect('blog:add-article')
        return render(request,'article-form.html',{'form':form})
    else:
        form=Article(instance=article)
        return render(request,'article-form.html',{'form':form})
    

def delete_article(request):
    article=get_object_or_404(Article,id=id)
    if article.author.user !=request.user:
        raise PermissionDenied()
    article.delete()
    return redirect("blog:blog")

def example(request):
    return render(request,"example.html")

canva/templates/blog-detail.html
{% extends 'layout/layout.html' %}
{% load static %}

{% block main %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h2 class="section-heading">{{ article.title }}</h2>
                    <p>{{ article.description }}</p>
                    <span class="caption text-muted">{{ article.created }}</span>
                    <span class="caption text-muted">{{ article.content }}</span>
                    <span class="caption text-muted">aaaaaa{{ article.author.user.username }}</span>
                   {% if article.image %}
                   
                   <img class="img-responsive" src="{{ article.image.url }}" style="width: 400px; height: 300px" alt="">
                   {% endif %}
                   {% if article.author == request.user.author %}
                
                   <a href="{% url 'blog:article_edit' id=article.id %}" style="background:green" class="badge bg-success">Edit</a>
                   <a href="{% url 'blog:delete_article' id=article.id %}" style="background:red" class="badge bg-danger">Delete</a>
               {% endif %}
                
                <div>View Count: {{article.view_count}}</div>
                </div>
            </div>
        </div>
    </article>

    <hr>
{% endblock main %}

canva/templates/blog.html
{% extends 'layout/layout.html' %}
{% load static %}


{% block main %}
{% static 'assets/img/about-bg.jpg' as blog_img %}
{% include 'includes/banner.html' with banner_image=blog_img banner_title='Blog Me' banner_description='Bura Blog sehifesidir'%}
    <!-- Main Content -->

    <div class="container">
        <div class="row">
            {% comment %} -------------- {% endcomment %}
            <div class="col-lg-2 col-lg-offset-2 col-md-2 ">
<div class="h1">Authors</div>
<ul class="list-unstyled">
    {% for author in authors %}
    <li><a href="?author={{author.user.username}}">{{author.user.get_full_name}}</a></li>
    
    {% endfor %}
</ul>
<hr>
<div>
    <h1>Tags</h1>
    <ul>

        {% for tag in tags  %}
        
        <li>
            <a href="?tag={{tags.title}}" class="badge bg-secondary">{{tag.title}}</a>    
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    {% if article.author == request.user.author %}
    
        <a href="{% url 'blog:edit-article' id=article.id %}" style="background:green" class="badge bg-success">Edit</a>
        <a href="{% url 'blog:delete-article' id=article.id %}" style="background:red" class="badge bg-danger">Delete</a>
    {% endif %}
</div>
<hr>

            </div>
            {% comment %} ............................ {% endcomment %}
            <div class="col-lg-8 col-lg-offset-2 col-md-10 ">
            {% for article in articles  %}
            <div class="post-preview">
                <a href="{% url 'blog:blog-detail' id=article.id %}">
                    <h2 class="post-title">
                      {{article.title}}
                    </h2>
                    <h3 class="post-subtitle">
                       {{article.description}}
                    </h3>   
                </a>
                </a>
                <p class="post-meta">Posted by <a href="#">{{article.author.user.username}}</a> on {{article.created}}</p>
            </div>
            <div>

            </div>

            </div>

            <hr>

            {% endfor %}
            
  
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
        <nav aria-label="...">
            <ul class="pagination">
                {% if page.has_previous %}
                <li class="page-item ">
                    <a class="page-link" href="?page={{page.previous_page_number}}">Previous</a>
                </li>

                {% else %}  
                     <li class="page-item disable">
                         <span class="page-link">Previous</span>
                     </li>
                {% endif %}
              {% for page_number in paginator.page_range %}
              
              <li class="page-item {% if page_number == page.number %}active{% endif %}"><a class="page-link" href="?page={{page_number}}">{{page_number}}</a></li>
              <li class="page-item active">
              {% endfor %}

              <li class="page-item">
                <a class="page-link" href="#">Next</a>
              </li>
            </ul>
          </nav>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>
    {% endblock main %}

canva/templates/contact.html
{% extends 'layout/layout.html' %}
 {% load static %} 
 {% block main %}

<!-- Main Content -->

{% static 'img/contact-bg.jpg' as contact_image %} 
{% include 'includes/banner.html' with banner_title='Contact Me' banner_description='Bura contact sehifesidir' banner_image=contact_image %}

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>
        Want to get in touch with me? Fill out the form below to send me a
        message and I will try to get back to you within 24 hours!
      </p>
      <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
      <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
      <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
      <form method="post" action="{% url 'info:confirm_contact' %}">
  {% csrf_token %}
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Name</label>
            <input
              type="text"
              class="form-control"
              placeholder="Name"
              name="name"
              id="name"
              required
              data-validation-required-message="Please enter your name."
            />
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Email Address</label>
            <input
              type="email"
              class="form-control"
              placeholder="Email Address"
              id="email"
              required
              name="email"

              data-validation-required-message="Please enter your email address."
            />
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Phone Number</label>
            <input
              type="tel"
              class="form-control"
              placeholder="Phone Number"
              id="phone"
              required
              name="phone"

              data-validation-required-message="Please enter your phone number."
            />
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Message</label>
            <textarea
              rows="5"
              class="form-control"
              placeholder="Message"
              id="message"
              required
              name="message"
              data-validation-required-message="Please enter a message."
            ></textarea>
            <p class="help-block text-danger"></p>
          </div>
        </div>
        <br />
        <div id="success"></div>
        <div class="row">
          <div class="form-group col-xs-12">
            <button type="submit" class="btn btn-default">Send</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock main %}

<hr />

canva/templates/home.html
{% extends 'layout/layout.html' %}


{% load static %}




{% block main %}



{%  static 'assets/img/about-bg.jpg' as home_image %}

{% include 'includes/banner.html' with banner_image=home_image banner_title='Home' banner_desc='bura home sehifesidir' %}


<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
</main>

{% endblock main %}