canva/blog/urls.py
from django.urls import path
from . import views

app_name='blog'


urlpatterns = [
    path("blog/",views.blog,name="blog"),
    path("blog_detail/<int:id>/",views.blog_detail,name="blog-detail"),
    path("article-form/",views.add_article,name="article-form"),
    path("edit-article/<int:id>/",views.article_edit,name="edit-article"),
    path("delete-article/<int:id>/",views.delete_article,name="delete-article"),
    path("example/",views.example,name="example"),
]

canva/canva/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("info.urls")),
    path('user/', include('user.urls')),
    path('blog/',include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canva/info/urls.py
from django.urls import path
from . import  views

app_name='info'
urlpatterns=[
    path('', views.home, name='home'),
    path("contact/",views.contact,name='Contact'),
    path("confirm-contact/",views.confirm_contact,name='confirm_contact'),
]

canva/user/urls.py
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('register/',views.register_view,name='register'),
    path('logout/',views.logout_view,name='logout'),
]

canva/templates/layout/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version) -->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap) -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'info:Contact' %}">Contact</a>
            </li>

            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:logout' %}">Lougut</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:register' %}">Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block main %}
    {% endblock %}

    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>